フックの設置
kakkun61/hedis pull request #1
Opened 2024-03-14 08:37 UTC by kakkun61

hs-opentelemetry-instrumentation-hedis を実装するためにフックを新たに設置する

*Do not merge*

2024-03-15 02:18 UTC, fumieval commented on src/Database/Redis/Connection.hs
> +            showString "connectHooks = _}"
Hooksを`show _ = "_"`で定義する方法では不十分でしょうか？

2024-03-15 02:19 UTC, fumieval commented on src/Database/Redis/Hooks.hs
> +type RecieveHook = IO Reply -> IO Reply
`s/Receive/Receive/`

2024-03-15 02:20 UTC, kakkun61 commented on src/Database/Redis/Connection.hs
> +            showString "connectHooks = _}"
それ採用で！

2024-03-15 02:22 UTC, kakkun61 commented on src/Database/Redis/Hooks.hs
> +type RecieveHook = IO Reply -> IO Reply
😣

2024-03-15 02:42 UTC, fumieval requested changes

2024-03-15 02:42 UTC, fumieval commented on src/Database/Redis/PubSub.hs
> +    ((), st') <- runStateT (modifyPending (updatePending cmd)) st
この関数においてフックすべきはCore.sendのみで、IOの絡まないmodifyPendingは除外した方がいいと思います。実装例

```haskell
sendCmd :: (Command (Cmd a b)) => Cmd a b -> StateT PubSubState Core.Redis ()
sendCmd DoNothing = return ()
sendCmd cmd       = do
  conn <- lift $ Core.reRedis $ asks Core.envConn
  let hook = Core.sendPubSubHook $ PP.hooks conn
  lift $ withRunInIO $ \runInIO -> hook (runInIO . Core.send) (redisCmd cmd : changes cmd)
  modifyPending (updatePending cmd)
```

2024-03-15 02:51 UTC, fumieval commented on src/Database/Redis/Hooks.hs
> +    , recieveHook :: ReceiveHook
ここがrecieveのままになっています

2024-03-15 05:04 UTC, kakkun61 commented on src/Database/Redis/Hooks.hs
> +    , recieveHook :: ReceiveHook
ｵｯ :bow:

2024-03-15 05:04 UTC, kakkun61 commented on src/Database/Redis/PubSub.hs
> +    ((), st') <- runStateT (modifyPending (updatePending cmd)) st
たし :crab:

2024-03-15 07:47 UTC, fumieval commented on src/Database/Redis/ProtocolPipelining.hs
> +    writeIORef connReplies rs
atomicModifyIORefにしましょう

2024-03-15 07:47 UTC, fumieval commented on src/Database/Redis/ProtocolPipelining.hs
> +    writeIORef connReplies rs
と思ったけれど元からこの実装か……

2024-03-15 08:19 UTC, fumieval approved these changes
よさそうです

2024-03-19 08:36 UTC, kakkun61 commented
PR した https://github.com/informatikr/hedis/pull/223

2024-03-19 08:36 UTC, closed without merging